image: docker:20.10.10

jdk8u301-jmx0.16.1:
  only:
    - tags
  before_script:
    - docker info
  script:
    - repository=$(awk '/FROM/{print $2}' Dockerfile.8u301)
    - docker build -t $HARBOR_HOST/library/${repository%.*}-jdk8u301-jmx0.16.1_$CI_COMMIT_TAG . -f Dockerfile.jdk8u301.jmx0.16.1
    - echo $HARBOR_PASS | docker login -u $HARBOR_USER $HARBOR_HOST --password-stdin
    - docker push $HARBOR_HOST/library/${repository%.*}-jdk8u301-jmx0.16.1_$CI_COMMIT_TAG
