image: docker:20.10.10
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
services:
  - docker:20.10.10-dind

stages:
  - build_and_push

before_script:
  - docker info

jdk8u152:
  stage: build_and_push
  tags:
    - dind
  only:
    - tags
  script:
    - repository=$(awk '/FROM/{print $2}' Dockerfile.8u152)
    - docker build -t $HARBOR_HOST/library/${repository%.*}-jdk8u152_$CI_COMMIT_TAG . -f Dockerfile.8u152
    - echo $HARBOR_PASS | docker login -u $HARBOR_USER $HARBOR_HOST --password-stdin
    - docker push $HARBOR_HOST/library/${repository%.*}-jdk8u152_$CI_COMMIT_TAG

jdk8u301:
  stage: build_and_push
  tags:
    - dind
  only:
    - tags
  script:
    - repository=$(awk '/FROM/{print $2}' Dockerfile.8u301)
    - docker build -t $HARBOR_HOST/library/${repository%.*}-jdk8u301_$CI_COMMIT_TAG . -f Dockerfile.8u301
    - echo $HARBOR_PASS | docker login -u $HARBOR_USER $HARBOR_HOST --password-stdin
    - docker push $HARBOR_HOST/library/${repository%.*}-jdk8u301_$CI_COMMIT_TAG