image: docker:20.10.10
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
services:
  - docker:20.10.10-dind

stages:
  - build_and_push

before_script:
  - docker info

jdk8:
  stage: build_and_push
  tags:
    - dind
  only:
    - tags
  script:
    - repository=$(awk '/FROM/{print $2}' Dockerfile)
    - docker build -t $HARBOR_REGISTRY/library/${repository%.*}-jdk8_$CI_COMMIT_TAG .
    - echo $HARBOR_PASS | docker login -u $HARBOR_USER $HARBOR_REGISTRY --password-stdin
    - docker push $HARBOR_REGISTRY/library/${repository%.*}-jdk8_$CI_COMMIT_TAG
